# Generated by Django 4.1.5 on 2023-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_cat', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=50)),
                ('course_des', models.TextField()),
                ('course_author', models.CharField(max_length=25)),
                ('course_author_img', models.CharField(max_length=50)),
                ('course_learner', models.IntegerField()),
                ('course_like', models.IntegerField()),
                ('course_price', models.CharField(max_length=10)),
                ('course_img', models.CharField(max_length=50)),
            ],
        ),
    ]
